# Uncomment the next line to define a global platform for your project
platform :ios, '14.3'

target 'dropspot' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for dropspot
pod 'MaterialComponents/schemes/Color'
pod 'MaterialComponents/AppBar'
pod 'MaterialComponents/Buttons'
pod 'MaterialComponents/Buttons+Theming'
pod 'MaterialComponents/TextControls+FilledTextAreas'
pod 'MaterialComponents/TextControls+FilledTextFields'
pod 'MaterialComponents/TextControls+OutlinedTextAreas'
pod 'MaterialComponents/TextControls+OutlinedTextFields'
pod 'MaterialComponents/TextControls+FilledTextAreasTheming'
pod 'MaterialComponents/TextControls+FilledTextFieldsTheming'
pod 'MaterialComponents/TextControls+OutlinedTextAreasTheming'
pod 'MaterialComponents/TextControls+OutlinedTextFieldsTheming'
pod 'MaterialComponents/Cards'
pod 'MaterialComponents/Slider'
pod 'MaterialComponents/Dialogs'
pod 'MaterialComponents/NavigationDrawer'
pod 'MaterialComponents/Snackbar'
pod 'MaterialComponents/ActivityIndicator'
pod 'MaterialComponents/ActivityIndicator+ColorThemer'

  target 'dropspotTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'dropspotUITests' do
    # Pods for testing
  end

end
