# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'dropspot' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for dropspot
pod 'MaterialComponents'

  target 'dropspotTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'dropspotUITests' do
    # Pods for testing
  end

end
